'use client';

import type { ModuleResult, Checkpoint, Signal } from '@marketing-alpha/types';
import { getTrafficLight } from '@marketing-alpha/types';
import { ModulePanel } from '@/components/os/window';
import { SignalBadge } from './signal-badge';
import { UnlockOverlay } from './unlock-overlay';
import { cn } from '@/lib/utils';

/**
 * GhostScan OS — Module Slide (Restyled)
 * ═══════════════════════════════════════════
 *
 * WHAT: Renders a single module's findings within the Dashboard window.
 * WHY:  The old version was a generic white card. Now it's a ModulePanel
 *       with retro bevel chrome, action title support, and GhostScan OS
 *       visual language (Plan Section 6).
 * HOW:  Uses <ModulePanel> from the OS component library. Data rendering
 *       logic is PRESERVED from original — checkpoints, signals, data
 *       entries, tool detection. Only the visual wrapper changed.
 *
 * Key change: Action titles. Instead of "DNS & Security" we show
 * "Your DNS configuration exposes 3 attack vectors." Generated by M41
 * for paid tier, or a template for free tier. This is the single most
 * impactful change — turning data dumps into editorial statements
 * (McKinsey technique, Plan Section 6).
 */

/* ── Types ──────────────────────────────────────────────────── */

interface ModuleSlideProps {
  moduleId: string;
  moduleName: string;
  result: ModuleResult | null;
  scanId: string;
  /** Whether this module requires payment to see full data */
  isPaid: boolean;
  /** McKinsey-style action title — the key insight sentence.
   *  Generated by M41 Module Synthesis or a template. */
  actionTitle?: string;
  /** Whether this is a GhostScan module (M09-M12) */
  isGhostModule?: boolean;
}

/* ── Helpers (preserved from original) ─────────────────────── */

/** Humanize camelCase keys: "dataLayerPresent" → "Data Layer Present" */
function humanizeKey(key: string): string {
  return key
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Format a primitive value for display */
function formatValue(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'number') return value.toLocaleString();
  if (typeof value === 'string') return value;
  return null;
}

/** Health → color class mapping (OKLCH tokens) */
const HEALTH_COLORS: Record<string, string> = {
  excellent: 'text-gs-terminal',
  good: 'text-gs-terminal/70',
  warning: 'text-gs-warning',
  critical: 'text-gs-critical',
  info: 'text-gs-mid-light',
};

/* ── Component ─────────────────────────────────────────────── */

export function ModuleSlide({
  moduleId,
  moduleName,
  result,
  scanId,
  isPaid,
  actionTitle,
  isGhostModule = false,
}: ModuleSlideProps) {
  const light = result?.score != null ? getTrafficLight(result.score) : undefined;
  const isError = result?.status === 'error';
  const health = light === 'green' ? 'green' : light === 'yellow' ? 'amber' : light === 'red' ? 'red' : undefined;

  /* Gather displayable data entries from result.data */
  const dataEntries: [string, string][] = [];
  if (result?.data) {
    for (const [key, val] of Object.entries(result.data)) {
      const formatted = formatValue(val);
      if (formatted != null) {
        dataEntries.push([humanizeKey(key), formatted]);
      }
    }
  }

  /* Tool signals */
  const toolSignals = result?.signals.filter((s) => s.type === 'tool_detected') ?? [];
  const freeSignalLimit = 3;
  const freeCheckpointLimit = 5;
  const hiddenCount = Math.max(
    0,
    (result?.signals.length ?? 0) - freeSignalLimit + dataEntries.length,
  );

  return (
    <div id={`slide-${moduleId}`} className="relative">
      <ModulePanel
        moduleId={moduleId}
        moduleName={moduleName}
        score={result?.score ?? undefined}
        health={health}
        actionTitle={actionTitle}
        isGhostModule={isGhostModule}
      >
        {/* Error state */}
        {isError && (
          <div className="flex items-center justify-center py-gs-8 font-data text-data-sm text-gs-mid">
            Module could not complete for this site.
          </div>
        )}

        {/* Paid user — full content */}
        {!isError && result && !isPaid && (
          <PaidContent result={result} dataEntries={dataEntries} toolSignals={toolSignals} />
        )}

        {/* Free user — limited content + redaction overlay */}
        {!isError && result && isPaid && (
          <FreeContent
            result={result}
            freeCheckpointLimit={freeCheckpointLimit}
            freeSignalLimit={freeSignalLimit}
            toolSignals={toolSignals}
          />
        )}

        {/* No data */}
        {!result && !isError && (
          <div className="flex items-center justify-center py-gs-8 font-data text-data-sm text-gs-mid">
            Awaiting data...
          </div>
        )}
      </ModulePanel>

      {/* Redaction overlay for free tier */}
      {isPaid && result && (
        <UnlockOverlay scanId={scanId} hiddenCount={hiddenCount > 0 ? hiddenCount : undefined} />
      )}
    </div>
  );
}

/* ── Full Content (Paid Users) ─────────────────────────────── */

function PaidContent({
  result,
  dataEntries,
  toolSignals,
}: {
  result: ModuleResult;
  dataEntries: [string, string][];
  toolSignals: Signal[];
}) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-gs-4">
      {/* Left: Checkpoints */}
      <div className="space-y-gs-3">
        {result.checkpoints.length > 0 && (
          <div>
            <h4 className="font-system text-os-xs text-gs-mid uppercase tracking-wider mb-gs-2">
              Checkpoints
            </h4>
            <div className="space-y-gs-2">
              {result.checkpoints.map((cp) => (
                <CheckpointRow key={cp.id} checkpoint={cp} showEvidence />
              ))}
            </div>
          </div>
        )}

        {result.signals.length > 0 && (
          <div>
            <h4 className="font-system text-os-xs text-gs-mid uppercase tracking-wider mb-gs-2">
              Signals
            </h4>
            <div className="flex flex-wrap gap-gs-1">
              {result.signals.map((signal, i) => (
                <SignalBadge key={`${signal.name}-${i}`} signal={signal} />
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Right: Tools + Data */}
      <div className="space-y-gs-3">
        {toolSignals.length > 0 && (
          <div>
            <h4 className="font-system text-os-xs text-gs-mid uppercase tracking-wider mb-gs-2">
              Detected Tools ({toolSignals.length})
            </h4>
            <div className="flex flex-wrap gap-gs-1">
              {toolSignals.map((s, i) => (
                <SignalBadge key={`tool-${s.name}-${i}`} signal={s} />
              ))}
            </div>
          </div>
        )}

        {dataEntries.length > 0 && (
          <div>
            <h4 className="font-system text-os-xs text-gs-mid uppercase tracking-wider mb-gs-2">
              Details
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-gs-4 gap-y-gs-1">
              {dataEntries.map(([label, value]) => (
                <div key={label} className="flex items-baseline justify-between font-data text-data-xs gap-gs-2">
                  <span className="text-gs-mid truncate">{label}</span>
                  <span className="text-gs-black font-bold text-right flex-shrink-0 max-w-[50%] truncate">
                    {value}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/* ── Limited Content (Free Tier) ───────────────────────────── */

function FreeContent({
  result,
  freeCheckpointLimit,
  freeSignalLimit,
  toolSignals,
}: {
  result: ModuleResult;
  freeCheckpointLimit: number;
  freeSignalLimit: number;
  toolSignals: Signal[];
}) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-gs-4">
      {result.checkpoints.length > 0 && (
        <div>
          <h4 className="font-system text-os-xs text-gs-mid uppercase tracking-wider mb-gs-2">
            Checkpoints
          </h4>
          <div className="space-y-gs-1">
            {result.checkpoints.slice(0, freeCheckpointLimit).map((cp) => (
              <CheckpointRow key={cp.id} checkpoint={cp} showEvidence={false} />
            ))}
          </div>
        </div>
      )}

      <div className="space-y-gs-3">
        {toolSignals.length > 0 && (
          <div>
            <h4 className="font-system text-os-xs text-gs-mid uppercase tracking-wider mb-gs-2">
              Detected Tools
            </h4>
            <div className="flex flex-wrap gap-gs-1">
              {toolSignals.slice(0, freeSignalLimit).map((s, i) => (
                <SignalBadge key={`tool-${s.name}-${i}`} signal={s} />
              ))}
              {toolSignals.length > freeSignalLimit && (
                <span className="font-data text-data-xs text-gs-mid self-center">
                  +{toolSignals.length - freeSignalLimit} more
                </span>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/* ── Checkpoint Row ────────────────────────────────────────── */

function CheckpointRow({
  checkpoint,
  showEvidence,
}: {
  checkpoint: Checkpoint;
  showEvidence: boolean;
}) {
  return (
    <div>
      <div className="flex items-center justify-between">
        <span className="font-data text-data-xs text-gs-black/80">{checkpoint.name}</span>
        <span className={cn(
          'font-data text-data-xs font-bold capitalize',
          HEALTH_COLORS[checkpoint.health] ?? 'text-gs-mid-light',
        )}>
          {checkpoint.health}
        </span>
      </div>
      {showEvidence && checkpoint.evidence && (
        <p className="font-data text-[11px] text-gs-mid mt-[2px] leading-relaxed">
          {checkpoint.evidence}
        </p>
      )}
      {showEvidence && checkpoint.recommendation && (
        <p className="font-data text-[11px] text-gs-cyan mt-[2px] leading-relaxed">
          → {checkpoint.recommendation}
        </p>
      )}
    </div>
  );
}
